### PR TITLE
polybar colorscheme

### PR DESCRIPTION
**Pull request by R0flcopt3r**
I'm opening this PR as it's strongly connected with PR https://github.com/srcery-colors/srcery-gui/pull/6.

I hope someone knows polybar better and can help make this a bit neater to "install".

### CODE REVIEW

**Comment by R0flcopt3r** [comment]
Latest commit makes it a lot easier to implement in any config.

**Comment by roosta** [comment]
I'm a bit short on time today, I'll give it a good look tomorrow. First impressions are good though. Maybe add i3 to the mix?

**Comment by roosta** [comment]
Maybe change the name of `bar/colors`, `module/colors`, and `module/bspwm-colors` to `bar/srcery`, `module/srcery`, and `module/bspwm-srcery` respectively. Its a bit confusing where the colors are coming from if they're just named `colors`. I'm also thinking that including bspwm at all is a bit opinionated, there's a lot of WM's out there, and if we include one, it could be argued that all of them should be included, which is a bit too much. How about just sticking to colors for the time being?

**Comment by R0flcopt3r** [comment]
I agree on the naming changes. 

I'll also agree that including WM specific this is out of scope. Could perhaps work up some folder structure for additional module specific schemes? And submit that as a separate PR.

I won't be able to work on it before Monday/Tuesday.

**Comment by roosta** [comment]
Folder structure could work. I also gave it some thought and I think its OK to include bspwm in the config. It is up to the user if they want to inherit after all.

**Comment by MindTooth** [comment]
Screengrabs?

**Pull request merged**
