### PR TITLE
Feat: Added srcery-intellij

### PR DESCRIPTION
**Pull request by nils-degroot**
Hi there. Some time ago I created a theme for Intellij IDEA for the srcery colorsschema. I added it as a submodule to the repository.

### CODE REVIEW

**Comment by nils-degroot** [comment]
That should be possible from my side. You want this on a repo within the srcery-colors org?

**Comment by roosta** [comment]
Yeah, better that than it being hidden away in another repo.

**Comment by nils-degroot** [comment]
Could you make a repo for me. Then I'll get the rest setup for it.

**Comment by roosta** [comment]
Sent you an invite just now. Once you've joined, I'll setup rights on the repo. Welcome!

**Comment by roosta** [comment]
https://github.com/srcery-colors/srcery-intellij
If you have any questions I'm usually online on discord, or open an issue or whatever you're comfortable with.

**Comment by nils-degroot** [comment]
Awesome, thanks. I'll get the Intellij store page update this week.

**Pull request closed without merging**
